@startuml

control Worker
database "Database \n (jobs)" as DB
control "Marktplaats Adapter" as Adapter
control "Notification Service" as Notification

Worker -> DB : load jobs
DB --> Worker

loop For each job

    Worker -> Adapter : fetch_listings(job)
    Adapter --> Worker : listings

    Worker -> DB : Update recent listing ids

    alt New listings found
        Worker -> Notification : Send notification
    end

end

@enduml