@startuml
left to right direction

actor User
actor Admin

rectangle "Marktplaats Watcher" {

  usecase "CRUD search job"

  usecase "View discovered listings"

  usecase "Subscribe to notifications"
  usecase "Receive listing notifications"

  usecase "Configure polling settings"
  usecase "Configure persistence settings"
}

User --> (CRUD search job)

User --> (View discovered listings)

User --> (Subscribe to notifications)
User --> (Receive listing notifications)

Admin --> (Configure polling settings)
Admin --> (Configure persistence settings)

@enduml